# Generated by Django 3.1.4 on 2020-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In the cart', 'In the cart'), ('Waiting for Payment', 'Waiting for Payment'), ('Preparation', 'Preparation'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default=('In the cart', 'In the cart'), max_length=200),
        ),
    ]
