# Generated by Django 3.1.4 on 2020-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201212_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
